name: dbt Docs Generation

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

env:
  DBT_PROFILES_DIR: "${{ github.workspace }}/.github"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Debug info
      run: |
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        echo "DBT_PROFILES_DIR: $DBT_PROFILES_DIR"
        ls -l $DBT_PROFILES_DIR
        cat $DBT_PROFILES_DIR/profiles.yml
        pip freeze | grep dbt
        pip freeze | grep duckdb
        dbt debug

    - name: dbt deps
      run: dbt deps

    - name: Build models
      run: dbt build

    - name: Generate dbt docs
      run: dbt docs generate

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: target

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
